Vagrant.configure('2') do |config|
 config.vm.define "technowl" do |technowl|
 technowl.vm.box = 'ubuntu/focal64'
 config.vm.box_download_insecure=true
config.vm.boot_timeout
technowl.vm.network "public_network", ip: "192.168.1.250", bridge: "Realtek PCIe GbE Family Controller"
 technowl.vm.provider "virtualbox" do |vb|
 vb.memory = '4000'
 vb.cpus = '4'
 end
technowl.vm.provision "shell", path: "setup.technowl.sh", privileged: true
 end
 end